[package]
name = "cdoc"
version = "0.1.0"
authors = ["Michael Zimmermann <sigmaepsilon92@gmail.com>"]
edition = "2018"

[dependencies]
clang = { version="^1.0", features=["clang_7_0"] }
serde = { version="^1.0", features=["derive"] }
serde_json = "^1.0"
tempfile = "^3.2"
thiserror = "^1.0"
